export const styles = {
  supportedPlatforms: { margin: "35px 0" },
  h1: { textAlign: "center", color: "#70A0FA" },
  platform: {
    width: "11rem",
    height: "7rem",
    border: "2px solid #e4e6e7",
    borderRadius: "20px",
    background: "linearGradient(145deg, #dae0e3, #ffffff)",
    boxShadow: " 20px 20px 21px #e3eaed,    -20px -20px 21px #ffffff",
  },
  platformContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0",
    padding: "0",
  },
  supPlatforms: {
    display: "flex",
    justifyContent: "space-around",
    flex: "wrap",
    alignItems: "center",
    margin: " 23px 0",
  },
  switch: {
    width: "100%",
    display: "flex",
    justifyContent: "end",
    padding: 0,
  },
  icon: { color: "white", fontSize: "2rem" },
  iconContainer: {
    width: "3rem",
    height: "3rem",
    backgroundColor: "#2f89ce",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    marginRight: "5px",
    padding: "0",
  },
  platformName: { marginLeft: "5px", fontSize: "14px" },
  onOff: { color: "#808080", fontWeight: "bold" },
};
